name: Build LaTeX document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          extra_system_packages: >
            texlive-latex-recommended
            texlive-latex-extra
            texlive-fonts-recommended
            texlive-pictures
            texlive-science
            texlive-xetex
            texlive-bibtex-extra
