name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install TeX Live (basic + extra packages for math/images)
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-science \
            texlive-fonts-extra \
            texlive-luatex \
            texlive-xetex \
            latexmk

      # 3. Compile LaTeX with latexmk (always clean first)
      - name: Compile LaTeX
        run: |
          latexmk -C        # Clean old aux files
          latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex

      # 4. Upload the resulting PDF
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: lecture-notes
          path: main.pdf
