name: Build and Deploy LaTeX PDF

on:
  push:
    branches: [ main ]  # Change if your default branch is not main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Compile PDF
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error main.tex
          pdflatex -interaction=nonstopmode -halt-on-error main.tex
          # Run twice for references, TOC, etc.

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: true
          allow_empty_commit: false
